const CaddieActionTypes = {
    TOGGLE_CADDIE_HIDDEN: 'TOGGLE_CADDIE_HIDDEN',
    AJOUTE_ITEM: 'AJOUTE_ITEM',
    DIMINUE_ITEM: 'DIMINUE_ITEM',
    SUPPRIME_ITEM_DU_PANIER: 'SUPPRIME_ITEM_DU_PANIER'
}

export default CaddieActionTypes